CREATE MATERIALIZED VIEW MV_DMITRIY_VISITS_AND_EATS AS
WITH PIZZERIA_IDS AS (
    SELECT
        MENU.PIZZERIA_ID
    FROM
        PERSON
    JOIN PERSON_VISITS ON PERSON.ID = PERSON_ID
    JOIN  MENU ON MENU.PIZZERIA_ID = PERSON_VISITS.PIZZERIA_ID
    WHERE
        NAME = 'Dmitriy' AND VISIT_DATE = '2022,01,08' AND PRICE < 800
)
SELECT
    NAME
FROM
    PIZZERIA_IDS
JOIN PIZZERIA ON PIZZERIA_ID = PIZZERIA.ID;

SELECT * FROM MV_DMITRIY_VISITS_AND_EATS
