SELECT
    COALESCE(PERSON.NAME, '-') AS PERSON_NAME,
    COALESCE(CAST(VISIT_DATE AS TEXT), 'null') AS VISIT_DATE,
    COALESCE(PIZZERIA.NAME, '-') AS PIZZERIA_NAME
FROM
    PERSON_VISITS
RIGHT JOIN PERSON ON PERSON.ID = PERSON_ID AND VISIT_DATE >= '2022,01,01' AND VISIT_DATE <= '2022,01,03'
FULL OUTER JOIN PIZZERIA ON PIZZERIA.ID = PIZZERIA_ID
ORDER BY
    PERSON_NAME,
    VISIT_DATE,
    PIZZERIA_NAME
