WITH PIZZERIA_IDS AS (
    SELECT
        PIZZERIA_ID
    FROM
        PERSON
    JOIN PERSON_VISITS ON PERSON.ID = PERSON_ID
    WHERE
        NAME = 'Dmitriy' AND VISIT_DATE = '2022,01,08'
)
SELECT
    NAME
FROM
    PIZZERIA_IDS
JOIN PIZZERIA ON PIZZERIA_ID = PIZZERIA.ID
