SELECT
    (SELECT
        NAME
    FROM
        PERSON
    WHERE
        PERSON_VISITS.PERSON_ID = ID
    ) AS PERSON_NAME,
    (SELECT
        NAME
    FROM
        PIZZERIA
    WHERE
        PERSON_VISITS.PIZZERIA_ID = ID
    )  AS PIZZERIA_NAME
FROM
    (SELECT
        *
    FROM
        PERSON_VISITS
    WHERE
        VISIT_DATE BETWEEN '2022,01,07' AND '2022,01,09'
    ) AS PERSON_VISITS
ORDER BY
    PERSON_NAME ASC,
    PIZZERIA_NAME DESC
