WITH KATE_VISITS AS (
    SELECT
        *
    FROM
        PERSON_VISITS
    JOIN PERSON ON PERSON_ID = PERSON.ID
    WHERE
        NAME = 'Kate'
)
SELECT
    PIZZA_NAME,
    PRICE,
    PIZZERIA.NAME AS PIZZERIA_NAME,
    VISIT_DATE
FROM
    MENU
JOIN KATE_VISITS ON KATE_VISITS.PIZZERIA_ID = MENU.PIZZERIA_ID 
JOIN PIZZERIA ON KATE_VISITS.PIZZERIA_ID = PIZZERIA.ID
WHERE
    PRICE BETWEEN 800 AND 1000
ORDER BY
    PIZZA_NAME,
    PRICE,
    PIZZERIA_NAME
