CREATE VIEW V_PRICE_WITH_DISCOUNT AS
SELECT
    NAME,
    PIZZA_NAME,
    PRICE,
    CAST((PRICE - PRICE * 0.1) AS BIGINT) AS DISCOUNT_PRICE
FROM
    PERSON_ORDER
    JOIN PERSON ON PERSON.ID = PERSON_ID
    JOIN MENU ON MENU.ID = MENU_ID
ORDER BY
    NAME,
    PIZZA_NAME;

SELECT * FROM V_PRICE_WITH_DISCOUNT
