WITH MALES_CTE AS (
    SELECT
        PIZZERIA.NAME AS PIZZERIA_NAME
    FROM
        PERSON_ORDER
    JOIN PERSON ON PERSON_ORDER.PERSON_ID = PERSON.ID
    JOIN MENU ON PERSON_ORDER.MENU_ID = MENU.ID
    JOIN PIZZERIA ON MENU.PIZZERIA_ID = PIZZERIA.ID
    WHERE
        PERSON.GENDER = 'male'
),

FEMALES_CTE AS (
    SELECT
        PIZZERIA.NAME AS PIZZERIA_NAME
    FROM
        PERSON_ORDER
    JOIN PERSON ON PERSON_ORDER.PERSON_ID = PERSON.ID
    JOIN MENU ON PERSON_ORDER.MENU_ID = MENU.ID
    JOIN PIZZERIA ON MENU.PIZZERIA_ID = PIZZERIA.ID
    WHERE
        PERSON.GENDER = 'female'
),

ONLY_MALES AS (
    SELECT * FROM MALES_CTE
    EXCEPT
    SELECT * FROM FEMALES_CTE
),

ONLY_FEMALES AS (
    SELECT * FROM FEMALES_CTE
    EXCEPT
    SELECT * FROM MALES_CTE
)

SELECT * FROM ONLY_MALES
UNION
SELECT * FROM ONLY_FEMALES
