WITH MENU_IDS AS (
    SELECT
        ID
    FROM
        MENU
    WHERE
        MENU.ID NOT IN (SELECT MENU_ID FROM PERSON_ORDER)
    ORDER BY
        ID
)
SELECT
    PIZZA_NAME,
    PRICE,
    PIZZERIA.NAME AS PIZZERIA_NAME
FROM
    MENU
JOIN MENU_IDS ON MENU.ID = MENU_IDS.ID
JOIN PIZZERIA ON MENU.PIZZERIA_ID = PIZZERIA.ID
ORDER BY
    PIZZA_NAME,
    PRICE
