SELECT
    *
FROM
    (SELECT
        PERSON.NAME AS PERSON_NAME,
        PIZZA_NAME,
        PIZZERIA.NAME AS PIZZERIA_NAME
     FROM
        PERSON
     JOIN PERSON_ORDER ON PERSON_ID = PERSON.ID
     JOIN MENU ON MENU.ID = MENU_ID
     JOIN PIZZERIA ON PIZZERIA.ID = PIZZERIA_ID
    ) AS RESULTS
ORDER BY
    PERSON_NAME,
    PIZZA_NAME,
    PIZZERIA_NAME
