WITH P_ID AS (
    SELECT
        PIZZERIA.ID
    FROM
        PIZZERIA
        JOIN MENU ON PIZZERIA.ID = MENU.PIZZERIA_ID
    WHERE 
        PRICE < 800 AND PIZZERIA.NAME = 'DoDo Pizza'
)
INSERT INTO PERSON_VISITS VALUES (
    (SELECT MAX(ID) FROM PERSON_VISITS) + 1,
    (SELECT ID FROM PERSON WHERE NAME = 'Dmitriy'),
    (SELECT * FROM P_ID),
    '2022,01,08'
);

REFRESH MATERIALIZED VIEW MV_DMITRIY_VISITS_AND_EATS;

SELECT * FROM MV_DMITRIY_VISITS_AND_EATS;

