WITH MALES_CTE AS (
    SELECT
        PIZZERIA.NAME AS PIZZERIA_NAME
    FROM
        PERSON_VISITS
    JOIN PERSON ON PERSON_VISITS.PERSON_ID = PERSON.ID
    JOIN PIZZERIA ON PERSON_VISITS.PIZZERIA_ID = PIZZERIA.ID
    WHERE
        PERSON.GENDER = 'male'
),

FEMALES_CTE AS (
    SELECT
        PIZZERIA.NAME AS PIZZERIA_NAME
    FROM
        PERSON_VISITS
    JOIN PERSON ON PERSON_VISITS.PERSON_ID = PERSON.ID
    JOIN PIZZERIA ON PERSON_VISITS.PIZZERIA_ID = PIZZERIA.ID
    WHERE
        PERSON.GENDER = 'female'
    ORDER BY
        PIZZERIA_NAME
),

ONLY_MALES AS (
    SELECT * FROM MALES_CTE
    EXCEPT ALL
    SELECT * FROM FEMALES_CTE
),

ONLY_FEMALES AS (
    SELECT * FROM FEMALES_CTE
    EXCEPT ALL
    SELECT * FROM MALES_CTE
)

SELECT * FROM ONLY_MALES
UNION ALL
SELECT * FROM ONLY_FEMALES
