CREATE VIEW V_SYMMETRIC_UNION AS 
WITH
R AS ( SELECT * FROM PERSON_VISITS WHERE VISIT_DATE = '2022,01,02'),
S AS ( SELECT * FROM PERSON_VISITS WHERE VISIT_DATE = '2022,01,06'),
R_1 AS ( SELECT * FROM R EXCEPT SELECT * FROM S),
S_1 AS ( SELECT * FROM S EXCEPT SELECT * FROM R)
SELECT
    PERSON_ID
FROM
    R_1
UNION
SELECT
    PERSON_ID
FROM
    S_1
ORDER BY
    PERSON_ID;

SELECT * FROM V_SYMMETRIC_UNION
