INSERT INTO PERSON_ORDER VALUES
(
    (SELECT MAX(ID) FROM PERSON_ORDER) + 1,
    (SELECT ID FROM PERSON WHERE NAME = 'Denis'),
    (SELECT ID FROM MENU WHERE PIZZA_NAME = 'sicilian pizza' LIMIT 1),
    '24,02,2022'
);

INSERT INTO PERSON_ORDER VALUES
(
    (SELECT MAX(ID) FROM PERSON_ORDER) + 1,
    (SELECT ID FROM PERSON WHERE NAME = 'Irina'),
    (SELECT ID FROM MENU WHERE PIZZA_NAME = 'sicilian pizza' LIMIT 1),
    '24,02,2022'
);
